# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{secrets.GIT_TO_DEV}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2 
      - id: files
        uses: Ana06/get-changed-files@v1.2
        with:
          format: 'csv'
          filter: '*.md'
      - run: |
          mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
          echo "::set-output name=FILES::${added_modified_files[@]}"
#          for added_modified_file in "${added_modified_files[@]}"; do
 #           echo "Do something with this ${added_modified_file}."
  #        done
      

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo ${{ steps.files.outputs.FILES }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo ${{ steps.files.outputs.FILES }},
          echo ${{ steps.files.outputs.added_modified }}
